name: FezDartBot
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.9.1 <3.0.0'

dependencies:
  dotenv: "^2.0.0"
  nyxx: "^1.0.0"
  nyxx_commander: "^1.0.0"
  time_ago_provider: "^2.0.4"
  intl: "^0.16.1"
  queries: "^0.1.14"